import { StyleSheet } from 'react-native';
import { colors } from '../colors';

export const JournalStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background.primary,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 15,
    backgroundColor: colors.background.secondary,
    borderBottomWidth: 1,
    borderBottomColor: colors.border.default,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.text.primary,
  },
  content: {
    flex: 1,
    padding: 20,
  },
  dateContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.background.secondary,
    padding: 12,
    borderRadius: 12,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: colors.border.light,
  },
  dateText: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.text.primary,
    marginHorizontal: 15,
  },
  moodContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 20,
  },
  moodButton: {
    width: 45,
    height: 45,
    borderRadius: 22.5,
    backgroundColor: colors.background.secondary,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: 'transparent',
  },
  moodButtonActive: {
    borderColor: colors.accent.primary,
    backgroundColor: colors.background.tertiary,
    transform: [{ scale: 1.1 }],
  },
  inputCard: {
    flex: 1,
    backgroundColor: colors.background.secondary,
    borderRadius: 16,
    padding: 15,
    borderWidth: 1,
    borderColor: colors.border.light,
  },
  titleInput: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.text.primary,
    backgroundColor: colors.background.tertiary,
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: colors.border.light,
    marginBottom: 5,
  },
  contentInput: {
    flex: 1,
    fontSize: 16,
    color: colors.text.primary,
    textAlignVertical: 'top',
    lineHeight: 24,
    paddingBottom: 25,
  },
  saveButton: {
    backgroundColor: colors.button.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 15,
    borderRadius: 12,
    marginTop: 20,
    gap: 10,
  },
  saveButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  authContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.background.primary,
    padding: 40,
  },
  authTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: colors.text.primary,
    marginTop: 20,
  },
  authDesc: {
    fontSize: 16,
    color: colors.text.secondary,
    textAlign: 'center',
    marginTop: 10,
    marginBottom: 30,
  },
  authButton: {
    backgroundColor: colors.button.primary,
    paddingHorizontal: 30,
    paddingVertical: 15,
    borderRadius: 12,
  },
  authButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  historyList: {
    padding: 20,
    paddingTop: 10,
  },
  monthSectionHeader: {
    backgroundColor: colors.background.primary,
    paddingVertical: 12,
    marginTop: 10,
    marginBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.border.light,
  },
  monthSectionText: {
    fontSize: 13,
    fontWeight: '900',
    color: colors.accent.primary,
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  entryCard: {
    backgroundColor: colors.background.secondary,
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: colors.border.light,
    flexDirection: 'row',
    alignItems: 'center',
  },
  entryTitleHistory: {
    fontSize: 16,
    fontWeight: '800',
    color: colors.accent.primary,
    marginBottom: 2,
  },
  sectionLabel: {
    color: colors.text.tertiary,
    fontSize: 11,
    fontWeight: '800',
    marginBottom: 8,
    marginTop: 15,
    letterSpacing: 1.5,
    textTransform: 'uppercase',
  },
  smallInputCard: {
    backgroundColor: colors.background.secondary,
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: colors.border.light,
    minHeight: 80,
  },
  entryContent: {
    flex: 1,
  },
  entryHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  entryDate: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.text.primary,
  },
  entryMood: {
    fontSize: 20,
  },
  entryPreview: {
    fontSize: 14,
    color: colors.text.secondary,
    lineHeight: 20,
  },
  deleteAction: {
    padding: 10,
    marginLeft: 10,
  },
  emptyState: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: 100,
  },
  emptyStateText: {
    fontSize: 16,
    color: colors.text.tertiary,
    marginTop: 15,
  },
  headerAction: {
    padding: 8,
    backgroundColor: colors.background.tertiary,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border.light,
  }
});
